spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shopping
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


jwt:
  secret: 8f1c31e4e0f85323df6588db01c11643e9764e8591353c0b8f13861e53f281bf